# Generated by Django 3.2.6 on 2021-09-30 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_remove_things_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='things',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='things',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
