# Generated by Django 3.2.6 on 2021-10-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_alter_panoimg_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panoimg',
            name='picture',
            field=models.ImageField(max_length=1000, upload_to='static/images/'),
        ),
    ]
