# Generated by Django 3.2.6 on 2021-10-04 03:53

from django.db import migrations, models
import world.models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_alter_panoimg_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='panoimg',
            name='picture_tn',
            field=models.ImageField(blank=True, help_text='Upload Pano Image Thumbnail', null=True, upload_to=world.models.PanoImg.upload_thumb, verbose_name='Pano Thumbnail'),
        ),
        migrations.AlterField(
            model_name='panoimg',
            name='picture',
            field=models.ImageField(blank=True, help_text='Upload Pano Image', null=True, upload_to=world.models.PanoImg.upload, verbose_name='Pano Img'),
        ),
    ]
